apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
      - name: gcp-ar-cred
      containers:
      - image: ${DOCKER_IMAGE_PATH}/worker:${DOCKER_IMAGE_TAG}
        name: worker
