name: GCP CI/CD

on:
  push:
    branches:
    - main
  pull_request:

env:
  TF_VERSION: 1.8.1
  TF_WORKSPACE: terraform
  TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
  TF_VAR_region: "asia-northeast1"
  TF_VAR_GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'


    steps:
    - name: Checkout
      uses: 'actions/checkout@v3'

    # - name: Setup Google Cloud Authentication 
    #   uses: 'google-github-actions/auth@v2'
    #   with:
    #     project_id: ${{ secrets.PROJECT_ID }}
    #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform -chdir=${{ env.TF_WORKSPACE }} init
     

    - name: Terraform Validate
      run: terraform -chdir=${{ env.TF_WORKSPACE }} validate -no-color 


    - name: Terraform Plan
      run: terraform -chdir=${{ env.TF_WORKSPACE }}  plan -no-color
      continue-on-error: false


    - name: Terraform Apply
      run: terraform -chdir=${{ env.TF_WORKSPACE }} apply -auto-approve
      # continue-on-error: false
      # env:
      #   GOOGLE_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}


    - name: Terraform Destroy
      run: terraform -chdir=${{ env.TF_WORKSPACE }} destroy -auto-approve
      # continue-on-error: false
      # env:
      #   GOOGLE_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
